repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.7.2
    hooks:
      - id: golangci-lint-fmt
      - id: golangci-lint-full

  - repo: https://github.com/godaddy/tartufo
    rev: v6.0.0
    hooks:
      - id: tartufo
